// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	IMAGES: R2Bucket;
	BUCKET_HOST: string;
	BUCKET_PREFIX: string;
}
